# Generated by Django 3.2 on 2022-11-22 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('featured_image', models.ImageField(blank=True, default='placeholder', null=True, upload_to='')),
                ('featured_image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image_alt_text', models.CharField(blank=True, default='aden wellness theme image', max_length=200)),
                ('header', models.CharField(blank=True, max_length=200)),
                ('text_background', models.IntegerField(choices=[(1, 'No background'), (2, 'Put background')], default=1)),
                ('excerpt', models.TextField(blank=True)),
                ('image_height', models.IntegerField(choices=[(40, '400px'), (32, '320px'), (27, '270px'), (20, '220px'), (16, '160px'), (8, '88px'), (5, '50px')], default=27)),
                ('image_place', models.IntegerField(choices=[(1, 'Image-as-background'), (2, 'Image-on-side')], default=1)),
                ('image_order', models.IntegerField(default=1)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['image_order'],
            },
        ),
    ]
