# Generated by Django 3.2 on 2022-11-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adenapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecontent',
            name='image_place',
        ),
        migrations.AddField(
            model_name='homecontent',
            name='button_text',
            field=models.CharField(default='See more', max_length=50),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='image_order',
            field=models.IntegerField(choices=[(1, 'First/only'), (2, 'Second'), (3, 'Third')], default=1),
        ),
        migrations.AlterField(
            model_name='homemedia',
            name='media_id',
            field=models.IntegerField(default=0),
        ),
    ]
