# Generated by Django 3.2 on 2022-12-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adenapp', '0003_remove_homecontent_text_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=200, unique=True)),
                ('doc_id', models.IntegerField(default=0)),
                ('doc_text', models.TextField(blank=True)),
            ],
        ),
    ]
