# Generated by Django 3.2 on 2022-12-01 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adenapp', '0004_sitedocs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteDocs',
        ),
    ]
