# Generated by Django 3.2 on 2022-12-14 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adenapp', '0006_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homemedia',
            old_name='media_id',
            new_name='media_pid',
        ),
    ]
